BuyalotV1.0/Controllers/ProductsController.cs
using BuyalotV1._0.DbConnection;
using BuyalotV1._0.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;
using BuyalotV1._0.Controllers;

namespace BuyalotV1._0.Controllers
{
    public class ProductsController : Controller
    {
        private DataContext Context { get; set; }
        private bool _DisposeContext = false;
        public int tempProdId;


        public ProductsController()
        {
            Context = new DataContext();
            _DisposeContext = true;
        }


        protected override void Dispose(bool disposing)
        {
            if (_DisposeContext)
                Context.Dispose();

            base.Dispose(disposing);

        }

        // GET: Product
        public ActionResult Index()
        {
            ViewBag.ProductList = Context.ProductModelSet.ToList();
            return View();
        }

        public ActionResult Cart()
        {
            try
            {
                ViewBag.cart = Session["Cart"];
            }
            catch (Exception)
            {

               
            }
           

            ViewBag.av = Session["avail"];
            return View();
        }

        public ActionResult Details(int? id, string searchString)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductModel product = Context.ProductModelSet.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }


            //if (!string.IsNullOrEmpty(searchString))
            //{
            //    HomeController hmC = new HomeController();

            //    try
            //    {
            //        return hmC.Index(searchString);
            //    }
            //    catch (InvalidOperationException)
            //    {

                    
            //    }
                
            //    //return 
            //}
            return View(product);
        }

        public ActionResult ViewProducts()
        {
            var product = (from p in Context.ProductModelSet
                           select p).ToList();
            return View(product);
        }

        

        public ActionResult AddProduct()
        {

            DataContext db = new DataContext();

            //IEnumerable<SelectListItem> items = new SelectList(db.ProductCategoryModelSet, "prodCategoryID", "categoryName");
            //ViewBag.prodCategoryID = items;

            ProductModel pro = new ProductModel();
            return View(pro);
        }


        [HttpPost]
        public ActionResult AddProduct(ProductModel product, HttpPostedFileBase upload)
        {
            var db = new DataContext();

            if (upload != null)
            {
                product.productImage = new byte[upload.ContentLength];
                upload.InputStream.Read(product.productImage, 0, upload.ContentLength);
            }
            db.ProductModelSet.Add(product);
            db.SaveChanges();

            return View(product);
        }


        public ActionResult populateDropDown()
        {
            List<SelectListItem> CustIDlistItems = new List<SelectListItem>();

            var getCategory = Context.ProductCategoryModelSet.ToList();
            foreach (var category in getCategory)
            {
                CustIDlistItems.Add(new SelectListItem
                {
                    Text = category.categoryName,
                    Value = category.prodCategoryID.ToString()
                });
            }

            ViewBag.CatList = CustIDlistItems;
            return View();
        }

        private int itemExist(int id)
        {
            List<Item> cart = (List<Item>)Session["Cart"];
            int counter = cart.Count;
            for (int i = 0; i < counter; i++)
            {
                if (cart[i].Prdcts.productID == id)
                {
                    return i;
                }
                ViewData["CartCount"] = cart.Count;
            }
            return -1;

        }

        //[Authorize(Roles = "CustomerViewModel")]
        public ActionResult AddToCart(int id)
        {
           
            if (Session["Cart"] == null)
            {
                List<Item> cart = new List<Item>();
                

                cart.Add(new Item(Context.ProductModelSet.Find(id), 1));
              
                Session["Cart"] = cart;
               // Session["cartCounter"] = cart.Count;
            }
            else
            {
                List<Item> cart = (List<Item>)Session["Cart"];

                int index = itemExist(id);

                if (index == -1)
                {
                    cart.Add(new Item(Context.ProductModelSet.Find(id), 1));
                    //Session["cartCounter"] = cart.Count;
                }
                else
                {
                    var getProduct = Context.ProductModelSet.Find(id);
                   
                    if (cart[index].Quantity < getProduct.quantityInStock)
                    {
                        cart[index].Quantity++;
                        Session["avail"] = null;
                    }
                    else
                    {
                        ViewBag.Availability = "we only have " + getProduct.quantityInStock + " " + getProduct.productName + " available in stock";
                        Session["avail"] = ViewBag.Availability;
                    }
                   

                    //if (Session["cartCounter"] == null)
                    //{
                    //    Session["cartCounter"] = cart.Count;
                    //}
                    //else
                    //{

                    //    var session = Session["cartCounter"];
                    //    Session["cartCounter"] = Convert.ToInt32(session) + cart[index].Quantity;
                    //}

                }

                Session["Cart"] = cart;
                ViewData["CartCount"] = cart.Count;
            }
          

                return View("AddToCart");
        }

        public ActionResult DeleteCart(int id)
        {
            List<Item> cart = (List<Item>)Session["Cart"];
            int index = itemExist(id);


            cart.RemoveAt(index);

            if(cart.Count < 1)
            {
                Session["cartCounter"] = 0;
            }

            Session["Cart"] = cart;

            return View("AddToCart");
        }

        public ActionResult UpdateQuantity(FormCollection fc)
        {
           

            string[] quantities = fc.GetValues("txtQuantity");

            string[] pids = fc.GetValues("pid");
            List<Item> cart = (List<Item>)Session["Cart"];
            int counter = cart.Count;

            for (int i = 0; i < counter; i++)
            {
                tempProdId = Convert.ToInt32(Session["tempProdId"]);
                var getProduct = Context.ProductModelSet.Find(Convert.ToInt32(pids[i]));


                if (Convert.ToInt32(quantities[i]) <= getProduct.quantityInStock)
                {
                    cart[i].Quantity = Convert.ToInt32(quantities[i]);
                    Session["avail"] = null;
                }
                else
                {
                    ViewBag.Availability = "we only have " + getProduct.quantityInStock + " " + getProduct.productName + " available in stock";
                    Session["avail"] = ViewBag.Availability;
                }


                Session["Cart"] = cart;
                ViewData["CartCount"] = cart.Count;
            }



            return View("AddToCart");
        }

        public ActionResult UpdatecartCounter()
        {

            List<Item> cart = (List<Item>)Session["Cart"];
            int counter = cart.Count;

            for (int i = 0; i < counter; i++)
                cart[i].Quantity++;
            Session["Cart"] = cart;
            ViewData["CartCount"] = cart.Count;

            return View("AddToCart");
        }

        //[HttpGet]
        //public ActionResult Payment()
        //{
        //    return View();
        //}
        [HttpPost]
        public ActionResult Payment()
        {
            string MERCHANT = "PHONE"
             , CURRENCY = "ZAR"
             , COUNTRY = "ZA"
             , REFERENCE = "TEST-001-001"
             , AMOUNT = "100.00"
             , PRIVATEKEY = "3912CB99-20A0-4F97-8D20-D9900F67A6A2"
             , FINAL_CONSISTENT_KEY = "";

            SHA512 SHA512HashCreator = SHA512.Create();

            StringBuilder concatenatedString = new StringBuilder();
            concatenatedString.Append(MERCHANT);
            concatenatedString.Append(CURRENCY);
            concatenatedString.Append(COUNTRY);
            concatenatedString.Append(REFERENCE);
            concatenatedString.Append(AMOUNT);
            concatenatedString.Append(PRIVATEKEY);

            byte[] EncryptedData = SHA512HashCreator.ComputeHash(Encoding.UTF8.GetBytes(concatenatedString.ToString()));

            StringBuilder CONSISTENT_KEY = new StringBuilder();

            for (int i = 0; i < EncryptedData.Length; i++)
            {
                CONSISTENT_KEY.Append(EncryptedData[i].ToString("X2"));
            }

            FINAL_CONSISTENT_KEY = CONSISTENT_KEY.ToString().ToUpper();
            return View();
        }

    }
}

BuyalotV1.0/Views/Products/AddToCart.cshtml
@using BuyalotV1._0.Models;
@{
    ViewBag.Title = "AddToCart";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Bootstrap -->
<link href="./Content/bootstrap-theme.css" rel="stylesheet" />
<link href="./Content/bootstrap.min.css" rel="stylesheet" />
<link href="./Content/stylesheet.css" rel="stylesheet" />

<link href="~/Content/dataTables.bootstrap.css" rel="stylesheet" />

<style type="text/css">
    .sid {
        position: relative;
        width: 100px;
        height: 50px;
        background-image: url('/Images/SID.png');
    }
</style>

<h1 style="color:#ff0000">@ViewBag.Availability</h1>
@using (Html.BeginForm("UpdateQuantity", "Products", FormMethod.Post))
{
    <div class="container">
        <h3 class="glyphicon glyphicon-shopping-cart"> Shopping Cart</h3>
        <br />
        <br />
        @{
            decimal sum = 0;
            String r = "R";
            int cartCount = 0;
        }
        <table class="table table-striped table-hover" id="myTable">
            <thead>
                <tr>
                    <th>Product</th>
                    <th>Vendor</th>
                    <th>Name</th>
                    <th>Price</th>
                    <th>Quantity<input type="submit" class="btn-primary" value="Update"/></th>
                    <th>SubTotal</th>
                    <th></th>
                </tr>
            </thead>

            <tbody>
                @foreach (Item p in (List<Item>)Session["Cart"])
                {

                    <tr>
                        @{

                            //var price = String.Format("{0:0.00}", p.Prdcts.price);
                            var base64 = Convert.ToBase64String(p.Prdcts.productImage);
                            var prodImage = string.Format("data:image/png;base64,{0}", base64);

                           
                            sum = sum + (p.Prdcts.price * p.Quantity);
                            cartCount = cartCount + p.Quantity;
                            Session["cartCounter"] = cartCount;
                        }

                        <td class="img-wrapper">
                            <img src="@prodImage" style="max-height:150px;max-width:150px;" class="img-responsive" id="myImg" />
                        </td>
                        <td>@p.Prdcts.vendor</td>
                        <td>@p.Prdcts.productName</td>
                        <td>R @String.Format("{0:0.00}", p.Prdcts.price)</td>
                        <td><input type="text" name="txtQuantity" id="txtQuantity" style="max-width:70px" value="@p.Quantity" />
                            <input type="hidden" name="pid" id="pid" value="@p.Prdcts.productID" />
                            
                                </td>
                        <td>R @String.Format("{0:0.00}", (p.Prdcts.price * p.Quantity))</td>
                        <td>
                            @Html.ActionLink("Delete", "DeleteCart", "Products", new { id = p.Prdcts.productID },
                        new { @class = "btn btn-danger glyphicon glyphicon-trash" })
                            @*/*  new { onclick = "return confirm('Are you sure you wish to delete?');" })*/*@
                        </td>
                        @*<td><button id="minus" class="btn glyphicon glyphicon-minus-sign"></button> <button id="plus" class="btn glyphicon glyphicon-plus-sign"></button></td>*@
                    </tr>

                            }

            </tbody>
            <tfoot>
                <tr>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th>Total Price</th>
                    <th><p>@r @String.Format("{0:0.00}", sum)</p></th>
                    <th></th>
                </tr>
            </tfoot>
        </table>
        <br />
        @Html.ActionLink("Continue Shopping", "Index", new { controller = "Home" }, new { @class = "btn btn-warning" })

        @if (Session["userID"] != null)
        {
         @Html.ActionLink("Proceed To CheckOut", "Payment", new { controller = "Order" }, new { @class = "btn btn-success pull-right" })
        }
        else
        {
            @Html.ActionLink("Proceed To CheckOut", "Login", new { controller = "Account" }, new { @class = "btn btn-success pull-right" })
        }

        @*@Html.ActionLink("Proceed To CheckOut", "Payment", new { controller = "Checkout" }, new { @class = "btn btn-success pull-right" })*@
       @*@using (Html.BeginForm("Payment", "Checkout", FormMethod.Post))
       {
        
       }*@

      
        
         @*<ul>
            
            <li>
                <a href="/#/login">CheckOut</a>
            </li>
        </ul>*@
        

    </div>
                            }

@*<FORM METHOD="POST" ACTION="https://www.sidpayment.com/paySID/">
    <INPUT TYPE="HIDDEN" NAME="SID_MERCHANT" VALUE="PHONEWAREHOUSE" />
    <INPUT TYPE="HIDDEN" NAME="SID_CURRENCY" VALUE="ZAR" />
    <INPUT TYPE="HIDDEN" NAME="SID_COUNTRY" VALUE="ZA" />
    <INPUT TYPE="HIDDEN" NAME="SID_REFERENCE" VALUE="REE384DJ" />
    <INPUT TYPE="HIDDEN" NAME="SID_AMOUNT" VALUE="129.00" />
    <INPUT TYPE="HIDDEN" NAME="SID_CONSISTENT" VALUE="DFIHFRUGTOSTERG" />
    <INPUT TYPE="submit" NAME="PaySID" class="pull-right" value="Checkout" />
</FORM>*@

<script src="~/Scripts/jquery.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/Scripts/jquery.dataTables.min.js"></script>
<script src="~/Scripts/dataTables.bootstrap.min.js"></script>


<script>
        $("#myTable").dataTable({
            "aoColumnDefs": [
               { 'bSortable': false, 'aTargets': [2, 3, 4, 5] }
            ],
            "aLengthMenu": [[5, 10, 25, -1], [5, 10, 25, "All"]],
            "iDisplayLength": 5
        });
</script>

BuyalotV1.0/Views/Products/Cart.cshtml
@using BuyalotV1._0.Models;
@{
    ViewBag.Title = "Cart";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Bootstrap -->
<link href="./Content/bootstrap-theme.css" rel="stylesheet" />
<link href="./Content/bootstrap.min.css" rel="stylesheet" />
<link href="./Content/stylesheet.css" rel="stylesheet" />

<link href="~/Content/dataTables.bootstrap.css" rel="stylesheet" />

<style type="text/css">
    .sid {
        position: relative;
        width: 100px;
        height: 50px;
        background-image: url('/Images/SID.png');
    }
</style>
<h1 style="color:#ff0000">@ViewBag.av</h1>
@using (Html.BeginForm("UpdateQuantity", "Products", FormMethod.Post))
{
    <div class="container">
        <h3 class="glyphicon glyphicon-shopping-cart"> Shopping Cart</h3>
        <br />
        <br />
        @{
            decimal sum = 0;
            String r = "R";
            int cartCount = 0;
        }
        <table class="table table-striped table-hover" id="myTable">
            <thead>
                <tr>
                    <th>Product</th>
                    <th>Vendor</th>
                    <th>Name</th>
                    <th>Price</th>
                    <th>Quantity<input type="submit" class="btn-primary" value="Update" /></th>
                    <th>SubTotal</th>
                    <th></th>
                </tr>
            </thead>

            <tbody>
                @try
                {
                    foreach (Item p in (List<Item>)ViewBag.cart)
                    {

                        <tr>
                            @{

                                //var price = String.Format("{0:0.00}", p.Prdcts.price);
                                var base64 = Convert.ToBase64String(p.Prdcts.productImage);
                                var prodImage = string.Format("data:image/png;base64,{0}", base64);


                                sum = sum + (p.Prdcts.price * p.Quantity);
                                cartCount = cartCount + p.Quantity;
                                Session["cartCounter"] = cartCount;
                            }
                            <td class="img-wrapper">
                                <img src="@prodImage" style="max-height:150px;max-width:150px;" class="img-responsive" id="myImg" />
                            </td>
                            <td>@p.Prdcts.vendor</td>
                            <td>@p.Prdcts.productName</td>
                            <td>R @String.Format("{0:0.00}", p.Prdcts.price)</td>
                            <td><input type="text" name="txtQuantity" id="txtQuantity" style="max-width:70px" value="@p.Quantity" /></td>
                            <td>R @String.Format("{0:0.00}", (p.Prdcts.price * p.Quantity))</td>
                            <td>
                                @Html.ActionLink("Delete", "DeleteCart", "Products", new { id = p.Prdcts.productID },
                        new { @class = "btn btn-danger glyphicon glyphicon-trash" })
                                @*/*  new { onclick = "return confirm('Are you sure you wish to delete?');" })*/*@
                            </td>
                            @*<td><button id="minus" class="btn glyphicon glyphicon-minus-sign"></button> <button id="plus" class="btn glyphicon glyphicon-plus-sign"></button></td>*@
                        </tr>

                                }
                                }
                                catch (NullReferenceException)
                                {

                                   
                                }
               

            </tbody>
            <tfoot>
                <tr>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th>Total Price</th>
                    <th><p>@r @String.Format("{0:0.00}", sum)</p></th>
                    <th></th>
                </tr>
            </tfoot>
        </table>
        <br />
        @Html.ActionLink("Continue Shopping", "Index", new { controller = "Home" }, new { @class = "btn btn-warning" })
        @if (Session["userID"] != null)
        {
            @Html.ActionLink("Proceed To CheckOut", "Payment", new { controller = "Order" }, new { @class = "btn btn-success pull-right" })
        }
        else
        {
            @Html.ActionLink("Proceed To CheckOut", "Login", new { controller = "Account" }, new { @class = "btn btn-success pull-right" })
        }
        @*@Html.ActionLink("Proceed To CheckOut", "Payment", new { controller = "Checkout" }, new { @class = "btn btn-success pull-right" })*@
        @*@using (Html.BeginForm("Payment", "Checkout", FormMethod.Post))
            {

            }*@



        @*<ul>

                <li>
                    <a href="/#/login">CheckOut</a>
                </li>
            </ul>*@


    </div>
                            }

@*<FORM METHOD="POST" ACTION="https://www.sidpayment.com/paySID/">
    <INPUT TYPE="HIDDEN" NAME="SID_MERCHANT" VALUE="PHONEWAREHOUSE" />
    <INPUT TYPE="HIDDEN" NAME="SID_CURRENCY" VALUE="ZAR" />
    <INPUT TYPE="HIDDEN" NAME="SID_COUNTRY" VALUE="ZA" />
    <INPUT TYPE="HIDDEN" NAME="SID_REFERENCE" VALUE="REE384DJ" />
    <INPUT TYPE="HIDDEN" NAME="SID_AMOUNT" VALUE="129.00" />
    <INPUT TYPE="HIDDEN" NAME="SID_CONSISTENT" VALUE="DFIHFRUGTOSTERG" />
    <INPUT TYPE="submit" NAME="PaySID" class="pull-right" value="Checkout" />
</FORM>*@

<script src="~/Scripts/jquery.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/Scripts/jquery.dataTables.min.js"></script>
<script src="~/Scripts/dataTables.bootstrap.min.js"></script>


<script>
        $("#myTable").dataTable({
            "aoColumnDefs": [
               { 'bSortable': false, 'aTargets': [2, 3, 4, 5] }
            ],
            "aLengthMenu": [[5, 10, 25, -1], [5, 10, 25, "All"]],
            "iDisplayLength": 5
        });
</script>

BuyalotV1.0/Views/Products/Details.cshtml
@using BuyalotV1._0.Models;
@model BuyalotV1._0.Models.ProductModel
@{
    ViewBag.Title = "Product Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="~/Scripts/bootstrap-formhelpers-countries.js"></script>
<div class="form-group">
    <h3><strong>Product Details</strong></h3>
    <hr />
    <div class="container">

        <div class="row">
            <div class="col-lg-3">
                <p>
                    @{

                        var base64 = Convert.ToBase64String(Model.productImage);
                        var prodImage = string.Format("data:image/png;base64,{0}", base64);

                        var price1 = Model.price.ToString();

                        var R = "R";
                        var price = R + "" + price1.ToString();
                    }
                    <img src="@prodImage" style="height:350px; width:300px" class="col-sm-5" />
                </p>
            </div>
            <div class="col-lg-6">
                <h3>@Html.DisplayFor(model => model.productName)</h3>
                <hr />
                <h3 style="color:#ff0000">@price</h3>
                <dl>

                    <dd>@Html.DisplayFor(model => model.vendor)</dd>
                    <dd>&#10004; Eligible for <b>Cash On Delivery</b></dd>
                    <dd><b>&#10004; Free Delivery Available</b></dd>
                    <dd><b>&#10004; Free Exchanges & Returns</b> for 30 days</dd>
                </dl>
            </div>
            <div class="col-lg-3">
                <div class="nav navbar-right" id="cartBox">
                    <h3 style="color:#ff0000">@price</h3>
                    <p>FREE DELIVERY</p>

                    @*<p>@Html.ActionLink("  AddToCart", "AddToCart", "Products", new { @class = "btn btn-success glyphicon glyphicon-shopping-cart" })</p>*@
                    @Html.ActionLink(" AddToCart", "AddToCart", "Products", new { id = Model.productID }, new { @class = "btn btn-success glyphicon glyphicon-shopping-cart" })
                    <br />
                    <br />
                    @Html.ActionLink(" AddToWishlist", "AddToWishlist", "ProductsWishlist", new { id = Model.productID }, new { @class = "btn btn-danger glyphicon glyphicon-heart" })

                </div>
            </div>
        </div>

    </div>
</div>


@*<p>
        <a class="glyphicon glyphicon-backward">@Html.ActionLink(" Back to products", "ViewProducts")</a>
    </p>*@


<div>
    <ul class="nav nav-tabs">
        <li class="active"><a data-toggle="tab" href="#ds">Description</a></li>
        <li><a data-toggle="tab" href="#info">Product Info</a></li>

    </ul>

    <div class="tab-content">
        <div id="ds" class="tab-pane fade in active">
            <p>@Html.DisplayFor(model => model.productDescription)</p>
        </div>

      
        <div id="info" class="tab-pane fade">
            <p>
                <b data-country="US" data-flags="true">Title:</b> @Html.DisplayFor(model => model.productName)
            </p>
            <p>
                <b>Brand:</b> @Html.DisplayFor(model => model.vendor)
            </p>
            <span class="bfh-countries" data-country="US" data-flags="true"></span>
        </div>
    </div>
</div>

BuyalotV1.0/Views/Products/Index.cshtml
@model BuyalotV1._0.Models.ProductModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<style type="text/css">
    #myImg {
        border-radius: 5px;
        cursor: pointer;
        transition: 0.3s;
    }

        #myImg:hover {
            opacity: 0.7;
        }

    /* The Modal (background) */
    .modal {
        display: none; /* Hidden by default */
        position: fixed; /* Stay in place */
        z-index: 1; /* Sit on top */
        padding-top: 100px; /* Location of the box */
        left: 0;
        top: 0;
        width: 100%; /* Full width */
        height: 100%; /* Full height */
        overflow: auto; /* Enable scroll if needed */
        background-color: rgb(0,0,0); /* Fallback color */
        background-color: rgba(0,0,0,0.9); /* Black w/ opacity */
    }

    /* Modal Content (image) */
    .modal-content {
        margin: auto;
        display: block;
        width: 80%;
        max-width: 700px;
    }

    /* Caption of Modal Image */
    #caption {
        margin: auto;
        display: block;
        width: 80%;
        max-width: 700px;
        text-align: center;
        color: #ccc;
        padding: 10px 0;
        height: 150px;
    }

    /* Add Animation */
    .modal-content, #caption {
        -webkit-animation-name: zoom;
        -webkit-animation-duration: 0.6s;
        animation-name: zoom;
        animation-duration: 0.6s;
    }



    /* The Close Button */
    .close {
        position: absolute;
        top: 15px;
        right: 35px;
        color: #f1f1f1;
        font-size: 40px;
        font-weight: bold;
        transition: 0.3s;
    }

     .close:hover,
     .close:focus {
            color: #bbb;
            text-decoration: none;
            cursor: pointer;
     }

     #myInput {
        background-image: url('/Images/search.png');
        background-position: 10px 12px;
        background-repeat: no-repeat;
        width: 100%;
        font-size: 16px;
        padding: 12px 20px 12px 40px;
        border: 1px solid #ddd;
        margin-bottom: 12px;
    }

    /* 100% Image Width on Smaller Screens */
</style>
<br />
<h3 style="border-bottom:solid 2px; border-bottom-color:dodgerblue">New Released Products</h3>
<br />
<div class="container" id="myTable">


    @foreach (var product in ViewBag.ProductList)
    {

        <div style="display:inline-block">
            @{
                var base64 = Convert.ToBase64String(product.productImage);
                var prodImage = string.Format("data:image/png;base64,{0}", base64);
                var prodID = product.productID;
                var name1 = product.vendor + " " + product.productName;
                //var price1 = product.price.ToString();
                var quantity1 = product.quantityInStock;
                var check1 = "";

            }

            <div class="img-wrapper">
                <img src="@prodImage" style="max-height:200px;max-width:200px;" class="img-responsive" id="myImg" />
            </div>

            <p>@name1</p>
            <p>R @String.Format(String.Format("{0:0.00}", product.price))</p>
            @if (quantity1 > 0)
            {
                check1 = "Available";
                //<p style="color:green"><b>check1</b></p>
                <p style="color:green"><b>@check1</b></p>
                @*<p>@Html.ActionLink("Add To Cart", "AddToCart", "Products", new { id = prodID }, new { @class = "btn btn-success" })</p>*@

            }
            else
            {

                check1 = "Out Of Stock";
                <p style="color:red"><b>@check1</b></p>
                @*<p>@Html.ActionLink("Add To WishList", "AddToCart", "Products", new { id = prodID }, new { @class = "btn btn-primary" })</p>*@

            }
            <p>@Html.ActionLink("AddToCart", "AddToCart", "Products", new { id = prodID }, new { @class = "btn btn-success glyphicon glyphicon-shopping-cart" })</p>
            <p>@Html.ActionLink("AddToWishList", "AddToWishlist", "ProductsWishlist", new { id = prodID }, new { @class = "btn btn-danger glyphicon glyphicon-heart-empty" })</p>


        </div>
                }
</div>

<div id="myModal" class="modal">
    <span class="close">X</span>
    <img class="modal-content" id="img01">
    <div id="caption"></div>
</div>

<script type="text/javascript">
// Get the modal
    var modal = document.getElementById('myModal');

    // Get the image and insert it inside the modal - use its "alt" text as a caption
    var img = document.getElementById('myImg');
    var modalImg = document.getElementById("img01");
    var captionText = document.getElementById("caption");
    img.onclick = function(){
        modal.style.display = "block";
        modalImg.src = this.src;
        captionText.innerHTML = this.alt;
    }

    // Get the <span> element that closes the modal
    var span = document.getElementsByClassName("close")[0];

    // When the user clicks on <span> (x), close the modal
    span.onclick = function() {
        modal.style.display = "none";
    }
</script>

<script type="text/javascript"> 
    function myFunction() {
        // Declare variables
        var input, filter, div, tr, td, i;
        input = document.getElementById("myInput");
        filter = input.value.toUpperCase();
        div = document.getElementById("myTable");
        tr = table.getElementsByTagName("tr");

        // Loop through all table rows, and hide those who don't match the search query
        for (i = 0; i < tr.length; i++) {
            td = tr[i].getElementsByTagName("td")[0];
            if (td) {
                if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
                    tr[i].style.display = "";
                } else {
                    tr[i].style.display = "none";
                }
            }
        }
    }

</script>