Admin/Controllers/HomeController.cs
using Admin.DbConnection;
using Admin.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Admin.Controllers
{
    
    public class HomeController : Controller
    {
        private DataContext Context { get; set; }
        private bool _DisposeContext = false;

        public HomeController()
        {
            Context = new DataContext();
            _DisposeContext = true;
        }
        protected override void Dispose(bool disposing)
        {
            if (_DisposeContext)
                Context.Dispose();

            base.Dispose(disposing);

        }
        public ActionResult Index()
        {
            int uid = Convert.ToInt32(Session["userID"]);

            var customer = (from c in Context.CustomerModelSet
                            select c).ToList();
            Session["CusCount"] = customer.Count;

            var category = (from c in Context.ProductCategoryModelSet
                            select c.prodCategoryID).ToList();
            Session["CatCount"] = category.Count;

            var prod = (from c in Context.ProductModelSet
                           select c.productID).ToList();
            Session["ProdCount"] = prod.Count;

            var orderCount = (from o in Context.OrderModelSet
                              where o.customerID == uid
                              join od in Context.OrderDetailsModelSet
                              on o.orderID equals od.orderID
                              join p in Context.ProductModelSet
                              on od.productID equals p.productID
                              select new OrderList
                              {
                                  customerID = o.customerID,
                                  orderDate = o.orderDate,
                                  shippingDate = o.shippingDate,
                                  shippingAddress = o.shippingAddress,
                                  status = o.status,
                                  quantityOrdered = od.quantityOrdered,
                                  priceEach = od.priceEach,
                                  productName = p.productName
                              }).Count();

            Session["OrderCount"] = orderCount;

            var subscriber = (from c in Context.SubscribeModelSet
                               select c.subscribeID).ToList();
            Session["SubCount"] = subscriber.Count;

            ViewBag.prodCategoryID = new SelectList(Context.ProductCategoryModelSet, "prodCategoryID", "categoryName");
            var product = (from p in Context.ProductModelSet
                           select p).ToList();
            return View(product);
        }

        public ActionResult Create()
        {
            
            ViewBag.prodCategoryID = new SelectList(Context.ProductCategoryModelSet, "prodCategoryID", "categoryName");
            ProductModel pro = new ProductModel();
            return View(pro);
        }

        // POST: ProductsManager/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection, ProductModel product, HttpPostedFileBase upload)
        {
            var errors = ModelState
                    .Where(x => x.Value.Errors.Count > 0)
                    .Select(x => new { x.Key, x.Value.Errors })
                     .ToArray();

            if (ModelState.IsValid)
            {
                if (upload != null)
                {
                    product.productImage = new byte[upload.ContentLength];
                    upload.InputStream.Read(product.productImage, 0, upload.ContentLength);
                }
                Context.ProductModelSet.Add(product);
                Context.SaveChanges();
                ViewBag.result = "Product " + product.vendor + " " + product.productName + " Added Succesfully!";
                ViewBag.prodCategoryID = new SelectList(Context.ProductCategoryModelSet, "prodCategoryID", "categoryName", product.productID);

                return RedirectToAction("ViewProducts", "Product");
            }

            return View(product);

        }

    }
}

Admin/Controllers/ProductsManagerController.cs
using Admin.DbConnection;
using Admin.Models;
using Admin.Repository;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Admin.Controllers
{
    
    public class ProductsManagerController : Controller
    {
        
        Repository01 _repository = new Repository01();
        private DataContext Context { get; set; }
        private bool _DisposeContext = false;

        public ProductsManagerController()
        {
            Context = new DataContext();
            _DisposeContext = true;
        }
        protected override void Dispose(bool disposing)
        {
            if (_DisposeContext)
                Context.Dispose();

            base.Dispose(disposing);

        }



        //[Authorize(Roles = "Admin")]
        // GET: ProductsManager
        public ActionResult Index()
        {
            //ViewBag.prodCategoryID = new SelectList(Context.ProductCategoryModelSet, "prodCategoryID", "categoryName");
            var product = (from p in Context.ProductModelSet
                           select p).ToList();
            foreach (var item in product)
            {
                Session["ProdCount"] = product.Count;
            }
            return View(product);
        }

        // GET: ProductsManager/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductModel product = Context.ProductModelSet.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }


        public ActionResult ViewProducts()
        {
            ViewBag.prodCategoryID = new SelectList(Context.ProductCategoryModelSet, "prodCategoryID", "categoryName");
            var product = (from p in Context.ProductModelSet
                           select p).ToList();
            return View(product);
        }
        // GET: ProductsManager/Create
        public ActionResult Create()
        {
            ViewData["Categories"] = _repository.GetCategories();
            ViewBag.prodCategoryID = new SelectList(Context.ProductCategoryModelSet, "prodCategoryID", "categoryName");
            ProductModel pro = new ProductModel();
            return View(pro);
        }

        // POST: ProductsManager/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection, ProductModel product, HttpPostedFileBase upload)
        {
            var errors = ModelState
                    .Where(x => x.Value.Errors.Count > 0)
                    .Select(x => new { x.Key, x.Value.Errors })
                     .ToArray();

            if (ModelState.IsValid)
            {
                if (upload != null)
                {
                    product.productImage = new byte[upload.ContentLength];
                    upload.InputStream.Read(product.productImage, 0, upload.ContentLength);
                }
                Context.ProductModelSet.Add(product);
                Context.SaveChanges();
                ViewBag.result = "Product " + product.vendor + " " + product.productName + " Added Succesfully!";
                ViewBag.prodCategoryID = new SelectList(Context.ProductCategoryModelSet, "prodCategoryID", "categoryName", product.productID);

                return RedirectToAction("ViewProducts", "Product");
            }

            return View(product);

        }

        // GET: ProductsManager/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ViewBag.prodCategoryID = new SelectList(Context.ProductCategoryModelSet, "prodCategoryID", "categoryName");
            ProductModel product = Context.ProductModelSet.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: ProductsManager/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(/*[Bind(Include = "productID,productImage")] */ProductModel product, FormCollection collection, HttpPostedFileBase upload)
        {
            try
            {
                // TODO: Add update logic here

                if (ModelState.IsValid)
                {
                    if (upload != null)
                    {
                        product.productImage = new byte[upload.ContentLength];
                        upload.InputStream.Read(product.productImage, 0, upload.ContentLength);
                    }

                    Context.Entry(product).State = EntityState.Modified;
                    Context.SaveChanges();
                    ViewBag.result = "Product " + product.vendor + " " + product.productName + " Updated Succesfully!";
                    ViewBag.prodCategoryID = new SelectList(Context.ProductCategoryModelSet, "prodCategoryID", "categoryName", product.productID);
                    return View(product);

                }

                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Error", "Error");
            }
        }

        // GET: ProductsManager/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductModel product = Context.ProductModelSet.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: ProductsManager/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection, HttpPostedFileBase upload)
        {
            try
            {

                ProductModel product = Context.ProductModelSet.Find(id);
                if (upload != null)
                {
                    product.productImage = new byte[upload.ContentLength];
                    upload.InputStream.Read(product.productImage, 0, upload.ContentLength);
                }

                Context.ProductModelSet.Remove(product);
                Context.SaveChanges();
                ViewBag.result = "Product " + product.vendor + " " + product.productName + " Deleted Succesfully!";

                return RedirectToAction("Index");
            }

            catch
            {
                return RedirectToAction("Error", "Error");
            }
        }
    }
}

Admin/Views/Home/Category.cshtml
@{
    ViewBag.Title = "Category";
}

<h2>Category</h2>
<div class="crumb_nav"> <a href="@Url.Action("Index", "Home")">Home</a> &gt;&gt; @ViewBag.category.categoryName </div>

<div class="new_products">
    @foreach (var product in ViewBag.products)
    {
    <div class="new_prod_box">
        <a href="@Url.Action("Details", "Products", new { id = product.productID })">@product.productName</a>

        @{

            var base64 = Convert.ToBase64String(product.productImage);
            var prodImage = string.Format("data:image/png;base64,{0}", base64);


            var price1 = product.price.ToString();

            var R = "R";
            var price = R + "" + price1.ToString();
        }
        @*<img src="@prodImage" style="max-height:100px;max-width:100px;" />*@
        <div class="new_prod_bg">
            <a href="#">
                <img src="@prodImage" alt="@product.productName" class="thumb" border="0" />
            </a>
        </div>
    </div>
    }
</div>

Admin/Views/Home/Create.cshtml
@model Admin.Models.ProductModel

@{
    ViewBag.Title = "AddProduct";
}

<fieldset>
    <legend class="container">Add Product</legend>

    @using (Html.BeginForm("Create", "ProductsManager", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <br />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.productName, htmlAttributes: new { @class = "control-label col-sm-3" })
                <div class="col-sm-9">
                    @Html.EditorFor(model => model.productName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.productName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.productDescription, htmlAttributes: new { @class = "control-label col-sm-3" })
                <div class="col-sm-9">
                    @Html.EditorFor(model => model.productDescription, new { htmlAttributes = new { @class = "form-control"} })
                    @Html.ValidationMessageFor(model => model.productDescription, "", new { @class = "text-danger" })
                </div>
            </div>

           <div class="form-group">
            @Html.LabelFor(model => model.prodCategoryID, "prodCategoryID", htmlAttributes: new { @class = "control-label col-sm-3" })
            <div class="col-sm-9" id="ListId" height="10">
                @Html.DropDownList("prodCategoryID", "--Select Category--")
                @Html.ValidationMessageFor(model => model.prodCategoryID, "", new { @class = "text-danger" })
            </div>
        </div>

            <div class="form-group">
                @Html.LabelFor(model => model.vendor, htmlAttributes: new { @class = "control-label col-sm-3" })
                <div class="col-sm-9">
                    @Html.EditorFor(model => model.vendor, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.vendor, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.price, htmlAttributes: new { @class = "control-label col-sm-3" })
                <div class="col-sm-9">
                    @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control col-sm-3" } })
                    @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
                </div>

            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.quantityInStock, htmlAttributes: new { @class = "control-label col-sm-3" })
                <div class="col-sm-9">
                    @Html.EditorFor(model => model.quantityInStock, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.quantityInStock, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.productImage, htmlAttributes: new { @class = "control-label col-sm-3" })
                <div class="col-sm-9">
                    <input type="file" name="upload" id="upload" />
                </div>
            </div>


            <div class="col-sm-offset-3 col-sm-9">
                <input type="submit" value="Add Product" class="btn btn-primary" />
            </div>

        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
    <script language="javascript" type="text/javascript">
    $(document).ready(function () {
        $("#ListId").width(700);
    });
    </script>

</fieldset>

Admin/Views/Home/Index.cshtml
@model IEnumerable<Admin.Models.ProductModel>
@{
    ViewBag.Title = "Admin Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Bootstrap -->
<link href="./Content/bootstrap-theme.css" rel="stylesheet" />
<link href="./Content/bootstrap.min.css" rel="stylesheet" />
<link href="./Content/stylesheet.css" rel="stylesheet" />

<link href="~/Content/dataTables.bootstrap.css" rel="stylesheet" />

<link href="https://cdn.datatables.net/1.10.13/css/jquery.dataTables.min.css" type="text/css" rel="stylesheet" />
<link href="https://cdn.datatables.net/buttons/1.2.4/css/buttons.dataTables.min.css" type="text/css" rel="stylesheet" />
<link href="http://http://cdn.datatables.net/tabletools/2.2.4/css/dataTables.tableTools.css" type="text/javascript" rel="stylesheet" />


<style type="text/css">
    #myInput {
        background-image: url('/Images/search.png');
        background-position: 10px 12px;
        background-repeat: no-repeat;
        width: 100%;
        font-size: 16px;
        padding: 12px 20px 12px 40px;
        border: 1px solid #ddd;
        margin-bottom: 12px;
    }

    #myTable {
        /*border-collapse: collapse;*/
        width: 100%;
        border: 1px solid #ddd;
        font-size: 14px;
    }
</style>
<br />
<br />
<fieldset>
    @*<h1 class="container text-center" style="background-color:#70cef7">Product Dashboard</h1>*@
    <br />
    <button class="btn btn-default">
        @Html.ActionLink("Add New Product", "Create")
    </button>
    <br />
    <br />
    <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for products..">
    <br />
    <table class="table table-striped table-responsive table-bordered table-condensed" id="myTable">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.productName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.productDescription)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.price)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.vendor)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.quantityInStock)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.productImage)
                </th>
                <th width="200px">Action</th>
            </tr>
        </thead>
        
            @*<th>
                    @Html.DisplayNameFor(model => model.ProductCategory.categoryName)
                </th>*@
          <tbody>
              @foreach (var item in Model)
              {

                  var base64 = Convert.ToBase64String(item.productImage);
                  var prodImage = string.Format("data:image/png;base64,{0}", base64);

                  var name1 = item.vendor + " " + item.productName;
                  var price1 = item.price.ToString();
                  var quantity1 = item.quantityInStock;


                  var R = "R";
                  var price = R + "" + price1.ToString();



                  <tr>
                      <td>
                          @Html.DisplayFor(modelItem => item.productName)
                      </td>
                      <td class="text">
                          <span>
                              @Html.DisplayFor(modelItem => item.productDescription)
                          </span>
                      </td>
                      <td>
                          @price
                      </td>
                      <td>
                          @Html.DisplayFor(modelItem => item.vendor)
                      </td>
                      <td>
                          @Html.DisplayFor(modelItem => item.quantityInStock)
                      </td>
                      <td>
                          <img src="@prodImage" style="max-height:100px;max-width:100px;" />

                      </td>
                      <td>
                          @Html.ActionLink("Edit", "Edit", new { id = item.productID }) |
                          @Html.ActionLink("Details", "Details", new { id = item.productID }) |
                          @Html.ActionLink("Delete", "Delete", new { id = item.productID })
                      </td>
                  </tr>
              }
          </tbody>

    </table>
</fieldset>

<script src="~/Scripts/jquery.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/Scripts/jquery.dataTables.min.js"></script>
<script src="~/Scripts/dataTables.bootstrap.min.js"></script>

<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.4/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.4/js/buttons.flash.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>
<script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.24/build/pdfmake.min.js"></script>
<script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.24/build/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.4/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.4/js/buttons.print.min.js"></script>
<script src="http://cdn.datatables.net/buttons/1.2.4/js/buttons.colVis.min.js"></script>

<script type="text/javascript">
    function myFunction() {
        // Declare variables
        var input, filter, table, tr, td, i;
        input = document.getElementById("myInput");
        filter = input.value.toUpperCase();
        table = document.getElementById("myTable");
        tr = table.getElementsByTagName("tr");

        // Loop through all table rows, and hide those who don't match the search query
        for (i = 0; i < tr.length; i++) {
            td = tr[i].getElementsByTagName("td")[0];
            if (td) {
                if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
                    tr[i].style.display = "";
                } else {
                    tr[i].style.display = "none";
                }
            }
        }
    }

</script>




<script>
    //$("#myOrderTable").dataTable({
    //        "aoColumnDefs": [
    //           { 'bSortable': false, 'aTargets': [2, 3, 4, 5] }
    //        ],
    //        "aLengthMenu": [[5, 10, 25, -1], [5, 10, 25, "All"]],
    //        "iDisplayLength": 5
    //});


    var table = $('#myTable').DataTable({
        "aoColumnDefs": [
           { 'bSortable': false, 'aTargets': [0, 2, 3, 4, 6, 7] }
        ],//,
        //"aLengthMenu": [[5, 10, 25, -1], [5, 10, 25, "All"]],
        //"iDisplayLength": 5,
        dom: 'Bfrtip',
        buttons: [
            'copy',
            'print',
            'pdf'
        ]
        //dom: 'Bfrtip',
        //buttons: [
        //    'copy', 'pdf', 'print'
        //]
    });

    table.buttons().container()
   .appendTo('#myOrderTable_wrapper .col-md-6:eq(0)');
</script>