Admin/Controllers/ProductCategoriesManagerController.cs
using Admin.DbConnection;
using Admin.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Admin.Controllers
{
    
    public class ProductCategoriesManagerController : Controller
    {
        
        private DataContext Context { get; set; }
        private bool _DisposeContext = false;


        public ProductCategoriesManagerController()
        {
            Context = new DataContext();
            _DisposeContext = true;
        }


        protected override void Dispose(bool disposing)
        {
            if (_DisposeContext)
                Context.Dispose();

            base.Dispose(disposing);

        }
        // GET: ProductCategories
        public ActionResult Index()
        {
            var category = (from c in Context.ProductCategoryModelSet
                            select c.prodCategoryID).ToList();
            foreach (var item in category)
            {
                Session["CatCount"] = category.Count;
            }
            
            return View(Context.ProductCategoryModelSet.ToList());
        }

        // GET: ProductCategories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductCategoryModel productCategory = Context.ProductCategoryModelSet.Find(id);
            if (productCategory == null)
            {
                return HttpNotFound();
            }
            return View(productCategory);
        }

        //[Authorize(Roles = "Admin")]
        // GET: ProductCategories/Create
        public ActionResult Create()
        {
            ProductCategoryModel pro = new ProductCategoryModel();
            return View(pro);
        }

        // POST: ProductCategories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "prodCategoryID,categoryName")] ProductCategoryModel productCategory)
        {
            if (ModelState.IsValid)
            {
            //    productCategory.adminID = 1;
                Context.ProductCategoryModelSet.Add(productCategory);
                Context.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(productCategory);
        }

        // GET: ProductCategories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductCategoryModel productCategory = Context.ProductCategoryModelSet.Find(id);

            if (productCategory == null)
            {
                return HttpNotFound();
            }

            return View(productCategory);
        }

        // POST: ProductCategories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "prodCategoryID,categoryName")] ProductCategoryModel productCategory)
        {
            if (ModelState.IsValid)
            {
                Context.Entry(productCategory).State = EntityState.Modified;
                Context.SaveChanges();
                ViewBag.result = "Category " + productCategory.categoryName + " Updated Succesfully!";
                return View(productCategory);
            }

            return RedirectToAction("Index");
        }

        // GET: ProductCategories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductCategoryModel productCategory = Context.ProductCategoryModelSet.Find(id);
            if (productCategory == null)
            {
                return HttpNotFound();
            }
            return View(productCategory);
        }

        // POST: ProductCategories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ProductCategoryModel productCategory = Context.ProductCategoryModelSet.Find(id);
            Context.ProductCategoryModelSet.Remove(productCategory);
            Context.SaveChanges();
            ViewBag.result = "Category " + productCategory.categoryName + " Deleted Succesfully!";
            return View(productCategory);
        }

    }
}

Admin/Views/ProductCategoriesManager/Create.cshtml
@model Admin.Models.ProductCategoryModel

@{
    ViewBag.Title = "Create Category";
}


<fieldset>
    <legend class="container">Add Category</legend>

    @using (Html.BeginForm("Create", "ProductCategoriesManager", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <p style="color:green">@ViewBag.result<p />
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.categoryName, htmlAttributes: new { @class = "control-label col-sm-3" })
                    <div class="col-sm-9">
                        @Html.EditorFor(model => model.categoryName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.categoryName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-3 col-sm-9">
                        <input type="submit" value="Add Category" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
</fieldset>

Admin/Views/ProductCategoriesManager/Delete.cshtml
@model Admin.Models.ProductCategoryModel

@{
    ViewBag.Title = "Delete";
}

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend class="container">Delete Category</legend>
    <div>
        <p style="color:green">@ViewBag.result<p />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.categoryName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.categoryName)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-danger" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</fieldset>

Admin/Views/ProductCategoriesManager/Details.cshtml
@model Admin.Models.ProductCategoryModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Product Category</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.categoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.categoryName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.prodCategoryID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Admin/Views/ProductCategoriesManager/Edit.cshtml
@model Admin.Models.ProductCategoryModel

@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <p style="color:green">@ViewBag.result<p />
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.prodCategoryID)

        <div class="form-group">
            @Html.LabelFor(model => model.categoryName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.categoryName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.categoryName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Admin/Views/ProductCategoriesManager/Index.cshtml
@model IEnumerable<Admin.Models.ProductCategoryModel>

@{
    ViewBag.Title = "Product Category";
}
<!-- Bootstrap -->
<link href="./Content/bootstrap-theme.css" rel="stylesheet" />
<link href="./Content/bootstrap.min.css" rel="stylesheet" />
<link href="./Content/stylesheet.css" rel="stylesheet" />

<link href="~/Content/dataTables.bootstrap.css" rel="stylesheet" />

<style type="text/css">
    #myInput {
        background-image: url('/Images/search.png');
        background-position: 10px 12px;
        background-repeat: no-repeat;
        width: 100%;
        font-size: 16px;
        padding: 12px 20px 12px 40px;
        border: 1px solid #ddd;
        margin-bottom: 12px;
    }

    #myTable {
        /*border-collapse: collapse;*/
        width: 100%;
        border: 1px solid #ddd;
        font-size: 14px;
    }
</style>
<fieldset>
    <legend class="container">Category Information</legend>
    <br />
    <button class="btn btn-default">
        @Html.ActionLink("Add Product Category", "Create")
    </button>
    <br />
    <br />
    <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for category..">
    <br />
    <table class="table table-striped table-hover" id="myTable">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.categoryName)
            </th>
            <th>Action</th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.categoryName)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.prodCategoryID }) |
                    @*@Html.ActionLink("Details", "Details", new { id = item.prodCategoryID }) |*@
                    @Html.ActionLink("Delete", "Delete", new { id = item.prodCategoryID })
                </td>
            </tr>
        }

    </table>

</fieldset>

<script src="~/Scripts/jquery.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/Scripts/jquery.dataTables.min.js"></script>
<script src="~/Scripts/dataTables.bootstrap.min.js"></script>


<script>
        $("#myTable").dataTable({
            "aoColumnDefs": [
               { 'bSortable': false, 'aTargets': [2, 3, 4, 5] }
            ],
            "aLengthMenu": [[5, 10, 25, -1], [5, 10, 25, "All"]],
            "iDisplayLength": 5
        });
</script>

<script type="text/javascript">
    function myFunction() {
        // Declare variables
        var input, filter, table, tr, td, i;
        input = document.getElementById("myInput");
        filter = input.value.toUpperCase();
        table = document.getElementById("myTable");
        tr = table.getElementsByTagName("tr");

        // Loop through all table rows, and hide those who don't match the search query
        for (i = 0; i < tr.length; i++) {
            td = tr[i].getElementsByTagName("td")[0];
            if (td) {
                if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
                    tr[i].style.display = "";
                } else {
                    tr[i].style.display = "none";
                }
            }
        }
    }

</script>

   